### ISSUE TITLE
add missing beatmap packs

### ISSUE THREAD

**Issue by chasedigi** [Osekai/inex#31]
add https://osu.ppy.sh/beatmaps/packs/L25, https://osu.ppy.sh/beatmaps/packs/L26, https://osu.ppy.sh/beatmaps/packs/L27, and https://osu.ppy.sh/beatmaps/packs/L28 to
![image](https://github.com/user-attachments/assets/ff28e9cc-e764-42ca-8d79-5581bbd86285)

**Comment by chasedigi** [comment]
https://osu.ppy.sh/beatmaps/packs/F3 to 
![image](https://github.com/user-attachments/assets/0e02ea15-3d5e-4ee4-9634-f1bd1a249720)

**Comment by Tanza3D** [comment]
oh my god
this isn't a code issue and it's already at #15
